const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_LAN_HOST = "0.0.0.0";
const DEFAULT_PORT = 8765;
const DEFAULT_SERVER_URL = `http://${DEFAULT_HOST}:${DEFAULT_PORT}`;
const LOG_LIMIT = 1000;
const TERMINAL_REPLAY_LIMIT = 128 * 1024;

module.exports = {
  DEFAULT_HOST,
  DEFAULT_LAN_HOST,
  DEFAULT_PORT,
  DEFAULT_SERVER_URL,
  LOG_LIMIT,
  TERMINAL_REPLAY_LIMIT
};
